### ISSUE TITLE
Increasing claim creation limit not working

### ISSUE THREAD

**Issue by SnowBlitzz** [bloodmc/GriefDefender#171]
I've increased some player's create-limit by setting their LP meta, and rightfully so, /playerinfo shows that it has in fact increased, but they're still unable to create more claims than the base amount. Also, the error message doesn't show right.

![image](https://user-images.githubusercontent.com/7488382/79113027-8bb88d80-7db2-11ea-960c-aee855b9403d.png)

SpongeForge 7.2.0
Luckperms - Latest always
GD sponge 1.2.6 B4 (latest as of this posting)

**Comment by kencinder** [comment]
Please specify server platform, Luckperms and Griefdefender versions in use in your original post.

**Comment by SnowBlitzz** [comment]
Edited

**Comment by bloodmc** [comment]
You need to provide the exact LP command you are using to set their `create-limit` in LP.

**Comment by SnowBlitzz** [comment]
> You need to provide the exact LP command you are using to set their `create-limit` in LP.

I don't see how this is needed? When /playerinfo updates after I did the LP command that means it was correct, otherwise it would have stayed the same. 

/lp user <user> meta set griefdefender.create-limit 20 gd_claim_default=basic server=global

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/bloodmc/GriefDefender/commit/61a9d8efd1d03a7a3010828ef4b6992414cc73ae

**Comment by SnowBlitzz** [comment]
I've updated to 1.3.1 yesterday and this is still an issue. Changelog does not mention this fix either? Assuming you marked a wrong ticket
